# This is a basic workflow that is manually triggered

name: Create docs

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on: 
  workflow_dispatch:

jobs:
  createStubs:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    - name: Checkout PZEventDoc
      uses: actions/checkout@v3.5.2
        
    - name: Setup Python
      uses: actions/setup-python@v4.6.1
      with:
        python-version: '3.11'
        
    - name: Create Events.md
      run: python PZEventDoc.py -s 'data.json' -o 'docs/Events.md'
    
    - name: Commit changes
      run: |
        git config user.name [Bot]demiurgeQuantified
        git config user.email 8355611+demiurgeQuantified@users.noreply.github.com
        git commit "docs/Events.md" -m "Updated by Github Action"
        git push
